apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: plj56ixgk-go 
  janus-idp.io/tekton: plj56ixgk-go
  backstage.io/kubernetes-id: plj56ixgk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: plj56ixgk-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml