apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: plj56ixgk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: plj56ixgk-go 
  name: plj56ixgk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: plj56ixgk-go 
